text_prompt: [
              'a car driving in an empty street'
       ]

# Path configurations
ckpt_path: "../pretrained_models/lavie_base.pt"
output_folder: "../res/base/"
pretrained_path: "../pretrained_models"
train_data_dir: "/content/drive/My Drive/msvd_one"
output_dir: "/content/drive/My Drive/checkpoints"
cache_dir: null
logging_dir: "logs"

# Model configurations
model: UNet
video_length: 16
image_size: [320, 512]
pretrained_model_name_or_path: "../pretrained_models"
revision: null
variant: null

# Beta schedule
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"

# Model speedup
use_compile: false
use_fp16: true
mixed_precision: "fp16"
enable_xformers_memory_efficient_attention: false
allow_tf32: false

# Sample configurations
image_path: "/content/drive/My Drive/a_car_driving_in_empty_street.jpeg"
seed: null
run_time: 0
guidance_scale: 7.5
sample_method: 'ddpm'
num_sampling_steps: 50


# Dataset configurations
dataset_name: null
dataset_config_name: null
image_column: "image"
caption_column: "text"

# Training configurations
validation_prompt: null
num_validation_images: 4
validation_epochs: 1
max_train_samples: null
center_crop: false
random_flip: false
train_batch_size: 1
num_train_epochs: 10
max_train_steps: null
gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 1e-4
scale_lr: false
lr_scheduler: "cosine"
lr_warmup_steps: 500
snr_gamma: 5
use_8bit_adam: false
dataloader_num_workers: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
prediction_type: null
hub_model_id: null
report_to: "tensorboard"
local_rank: -1
checkpointing_steps: 500
checkpoints_total_limit: 3
resume_from_checkpoint: "latest"
noise_offset: 0
rank: 16 
resolution: 512
logging_steps: 200
gradient_analysis_steps: 10