name: lavie
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11.3
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pip:
      - accelerate==0.33.0
      - av==10.0.0
      - decord==0.6.0
      - einops==0.6.1
      - ffmpeg==1.4
      - imageio==2.31.1
      - imageio-ffmpeg==0.5.1
      - pandas==2.0.1
      - timm==0.6.13
      - tqdm==4.65.0
      - transformers==4.43.3
      - xformers==0.0.27.post2
      - omegaconf==2.3.0
      - natsort==8.4.0
      - rotary_embedding_torch
      - peft==0.12.0
      - opencv-python==4.10.0.84
      - huggingface-hub==0.24.5
      - numpy==1.21.6
      - torch==2.4.0
      - torchvision==0.19.0
      - einops==0.8.0
      - diffusers==0.16.0
      - omegaconf==2.3.0
      - imageio==2.34.2
      - 
